// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_h-knfhV9OC1vqO5IsMsNhammBXoSP8',
    appId: '1:379661837868:web:81d48b2532275e078b5389',
    messagingSenderId: '379661837868',
    projectId: 'smartapp-a327e',
    authDomain: 'smartapp-a327e.firebaseapp.com',
    storageBucket: 'smartapp-a327e.appspot.com',
    measurementId: 'G-SDT0QV2Z08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ZKnHVkaPkOOne7RkDlvSX7BxosztxfU',
    appId: '1:379661837868:android:5992e44bbdbec8208b5389',
    messagingSenderId: '379661837868',
    projectId: 'smartapp-a327e',
    storageBucket: 'smartapp-a327e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9K_BGtP0K5F6gb0poQx_DuS6CPLr7XRA',
    appId: '1:379661837868:ios:c3507fd397d50af88b5389',
    messagingSenderId: '379661837868',
    projectId: 'smartapp-a327e',
    storageBucket: 'smartapp-a327e.appspot.com',
    iosBundleId: 'com.quizz.smartapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9K_BGtP0K5F6gb0poQx_DuS6CPLr7XRA',
    appId: '1:379661837868:ios:717dd371f69067df8b5389',
    messagingSenderId: '379661837868',
    projectId: 'smartapp-a327e',
    storageBucket: 'smartapp-a327e.appspot.com',
    iosBundleId: 'com.quiz.SmartAppdaily',
  );
}
